### ISSUE TITLE
AutoCryptoMine won't let me configure my mining software.

### ISSUE THREAD

**Issue by Dosentos** [GitMag/AutoCryptoMine#3]
AutoCryptoMine opens my mining software but won't let me move my mouse.

*This is intended behaviour normally*, but in some cases AutoCryptoMine should support better the configuration of the mining apps. 

I launched the app, waited the inactive time and watched how my mining program started.

Normally it would go straight to mining but instead it asked me my account info like I was opening the mining software for the first time. I realized I didn't have my wallet hash on my clipboard, so I moved my mouse and the mining app shut down. So I can't use the tool at the moment.

Instead of this behaviour AutoCryptoMine could solve this by
- adding few additional field `browse your config.txt file...`
OR
-  Adding a new button (or smth like that) that sets AutoCryptoMine to kind of manual mode. It opens the mining software and let's user test it.

**Comment by GitMag** [comment]
I get what you mean, but i don't really know how to make it work with a config file. I'm really new to c# coding and this is my first program. I will have to investigate further.

**Comment by GitMag** [comment]
I resolved this issue, i will add a feature later, but for now you need to copy the Miner config file to the same directory as AutoCryptoMiner is located in.
