### ISSUE TITLE
AutoCryptoMine starts my mining app while I'm coding

### ISSUE THREAD

**Issue by Dosentos** [GitMag/AutoCryptoMine#4]
At the moment AutoCryptoMine starts when I'm not using my mouse for xx period. This is problematic when writing a long issue to github or coding or writing an email. 

So it should probably listen for keypresses too.
I recommend adding complete function for checking if keys have been pressed for xx period.

**Comment by GitMag** [comment]
Thanks for the suggestion! I will add it for the next release

**Comment by GitMag** [comment]
Added keyboardhook
